export const POSTS_TYPE = {
  POSTS_LOADED_SUCCESS: "POSTS_LOADED_SUCCESS",
  POSTS_LOADED_FAIL: "POSTS_LOADED_FAIL",
  ADD_POST: 'ADD_POST',
  DELETED_POST: 'DELETED_POST',
  UPDATE_POST: 'UPDATE_POST',
  FIND_POST: 'FIND_POST',

};
